### PR TITLE
feat(templateFunction): Add support for template function 

### PR DESCRIPTION
**Pull request by ludohenin**
Original PR: #22

### CODE REVIEW

**Comment by NathanWalker** [comment]
excellent @ludohenin lgtm!! thank you thank you!!

**Comment by ludohenin** [comment]
Published and tagged 1.1.0

**Comment by NathanWalker** [comment]
You're the best thanks again!

**Comment by NathanWalker** [comment]
That pesky console.log statement:
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L133
Not huge deal... If you make me a collab on repo and npm I can help take care of lil stuff like this...

**Comment by ludohenin** [comment]
Thanks for the catch.
Cleaned and published 1.1.1
Have added you as collab on Github
What's your npm username ?

**Comment by NathanWalker** [comment]
walkerrunpdx

**Comment by ludohenin** [comment]
done.

**Comment by NathanWalker** [comment]
Thanks, I'll keep an eye on things and we can work together to process things here.
It's a great toolchain plugin.

**Pull request merged**
