### PR TITLE
feat: Add support for preprocessors

### LINKED ISSUE #11: Please add stylus support
Or provide a generic means to add compiler support. AFAIK because of express.js most preprocessors use an identical syntax for compilation.

### PR DESCRIPTION
**Pull request by ludohenin**
- [x] Add HTML and CSS preprocessors support.
- [x] Drop Jade - use htmlPreprocessor instead
- [x] Support SASS

Once ready, I'm going to release as 1.0.0 due to the breaking changes.

Should fix #11 #14

### CODE REVIEW

**Comment by nareshbhatia** [comment]
@ludohenin, the issue is in this part of the code (parser.js):

    urls.forEach(function (url) {
      var file = getFile(url);
      if (HTML && opts.htmlPreprocessor) {
        file = require(opts.htmlPreprocessor.require).render(file, opts.htmlPreprocessor.options);
      }
      if (CSS && opts.cssPreprocessor) {
        file = require(opts.cssPreprocessor.require).render(file, opts.cssPreprocessor.options);
      }
      assetFiles += file;
    });

You are assuming that `htmlPreprocessor` and `cssPreprocessor` have a method called render that takes two parameters - file and options. While this is true for jade and stylus it is not true for node-sass. While node-sass has a `render` function, it is asynchronous and requires a callback. There is a sync version called `renderSync()` but its argument do not match what you have.

I think one way to solve this is to change your API to accept a callback. Thus the caller specifies how to make the preprocessor call instead of the parser code.

I will work on a change and send you a pull request.

**Comment by ludohenin** [comment]
so could just simply make it like this
```
{
  // ...
  cssPreprocessor: function (sourceFile: string) {
    // ... implementation (sync only)
    return compiledSting: string;
  }
}
```

**Comment by nareshbhatia** [comment]
Exactly, that's what I was thinking. Furthermore, since we are introducing breaking changes, I would suggest using this opportunity to simplify the API significantly. This is what I propose:

Let's abstract the API a bit - let's not use the terms `html` and `css`. Since this plugin is all about processing `templateUrl` and `styleUrls` inside `components`, let's only use the terms `templates`, `styles` and `components`.

Thus the callbacks would be something like:

    var options = {
        templateProcessor: function (templateType: string, sourceString: string) {
            // sync implementation
            return processedString;
        },

        styleProcessor: function (styleType: string, sourceString: string) {
            // sync implementation
            return processedString;
        },
    }

The advantage of this change is that you can drop bunch of options and simplify the API.

- You don't need `html` and `css` booleans options anymore. If caller supplies `templateProcessor` and/or `styleProcessor`, that means they want to process `templateUrl` and/or `styleUrls`, otherwise not. Moreover, since we are supplying the `templateType` and `styleType`, they can decide whether the `sourceString` needs to be preprocessed or not, and if yes, which preprocessor they should run. Now we can have a mix of `.css` and `.scss` in `styleUrls` and we can let `.css` pass through with no change, but preprocess `.scss` with the correct preprocessor.

- Don't need `htmlExtension` - the plugin doesn't care about specific extensions. All it needs to do is to supply the extension to the callback.

Based on this, the default options now look like this:

    var defaults = {
        base: '/',
        target: 'es6',
        indent: 2,
        useRelativePaths: false,
        removeLineBreaks: false,
        templateProcessor: false,
        styleProcessor: false
    };

Based on this I would also suggest renaming the fixture files as follows:

- `component_<template-type>_<style-type>`, e.g. `component_html_css`
- `template.<template-type>`, e.g. `template.html`
- `styles.<style-type>`, e.g. `styles.css`
- `result_expected_<template-type>_<style-type>`, e.g. `result_expected_html_css`
- `result_actual_<template-type>_<style-type>`, e.g. `result_actual_html_css`

Also suggest adding `test/fixtures/result_actual*` to `.gitignore` so that it does not get committed accidentally.

Please let me know what you think.

**Comment by ludohenin** [comment]
@nareshbhatia I'll make the changes according to you proposition.

**Comment by nareshbhatia** [comment]
Awesome! Thank you.

**Comment by ludohenin** [comment]
It's here. I haven't done all the cleanup you suggested but the essential is here.
I had to keep the `templateExtension` conf prop as I'm relying upon it in the RegExp.

**Comment by ludohenin** [comment]
Published on npm as 1.0.0

**Comment by nareshbhatia** [comment]
Thanks. Looks great!

**Comment by nareshbhatia** [comment]
@ludohenin, will you be creating a PR to angular2-seed to update to this version?

**Pull request merged**
