### PR TITLE
Add sourcemap support

### LINKED ISSUE #16: Sourcemap support?
@ludohenin: this plugin is great! thanks! when is the support for source-maps coming?

### PR DESCRIPTION
**Pull request by dhilgarth**
Fixes #16

### CODE REVIEW

**Comment by ludohenin** [comment]
@dhilgarth thanks for you PR but the build is failing. I haven't check what could be the cause, can you have a look ?

**Comment by dhilgarth** [comment]
Well, I already checked that when I created the PR, and as far as I can tell, the code is fine. It compiles locally, and the error message is strange:

```SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode```

But strict mode is used: https://github.com/dhilgarth/gulp-inline-ng2-template/blob/59df36c41d92b160ce91d17542ae0d93e880f626/test/test.js#L1

So, it looks more like a configuration problem on the build server?

**Comment by ludohenin** [comment]
maybe you can try to update the travis config to use node 8

**Comment by ludohenin** [comment]
Thanks for the PR!
the issue was with node version (probably in a dependency)

**Comment by dhilgarth** [comment]
Nice, thanks :)

**Pull request merged**
